services:
  - type: web
    name: community-app
    env: node
    plan: free

    buildCommand: |
      npm install
      cd backend && npm install
      cd ../frontend && npm install && npm run build

    startCommand: cd backend && npm start

    envVars:
      - key: NODE_VERSION
        value: 18.17.0

      - key: PORT
        value: 10000

      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET_KEY
        sync: false

      - key: FRONTEND_URL
        value: https://community-app.onrender.com
